#! /usr/bin/python3

from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer

# HOST = '175.24.40.189'
HOST = '172.17.0.8'
PORT = 6000

#实例化虚拟用户，这是FTP验证首要条件
authorizer = DummyAuthorizer()

#添加用户权限和路径，括号内的参数是(用户名， 密码， 用户目录， 权限)
authorizer.add_user('lzj', 
                    'zijianlv', 
                    '/home/ubuntu/monit_log', 
                    perm='elradfmw')

#初始化ftp句柄
handler = FTPHandler
handler.authorizer = authorizer

#监听ip 和 端口
server = FTPServer((HOST, PORT), handler)

#开始服务
server.serve_forever()